language: node_js

node_js:
  - "10.15"

script:
  - echo "Deploy"

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --project "nuxt-app-6f771" --token "1/TCrGae2Ec2NFdPTLOl8p-CKmKIHUXi0Fa3Bvgg0ROA8"