export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const INIT_TODO = 'INIT_TODO'
export const INIT_MEETUP = 'INIT_MEETUP'
export const CREATE_MEETUP = 'CREATE_MEETUP'
export const CREATE_IMGDATAS = 'CREATE_IMGDATAS'
